version: '2'

networks:
  test:

services:

  ca_hospital:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hospital.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1010
    ports:
      - "1010:1010"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/hospital:/etc/hyperledger/fabric-ca-server
    container_name: ca.hospital.com
    hostname: ca.hospital.com
    networks:
      - test