NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-3010-ca-laboratory-com.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-3010-ca-laboratory-com.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-3010-ca-laboratory-com.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-3010-ca-laboratory-com.pem
    OrganizationalUnitIdentifier: orderer
