version: "2"

networks:
  test:

services:
  # ca-org3:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.laboratory.com
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.laboratory.com-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.laboratory.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "9054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../../artifacts/channel/crypto-config/peerOrganizations/laboratory.com/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ../../artifacts/channel/crypto-config/peerOrganizations/laboratory.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.laboratory.com
  #   hostname: ca.laboratory.com
  #   networks:
  #     - test

  mysql4:
    container_name: mysql4
    image: mysql
    environment:
      - MYSQL_PASSWORD=Ron1234.
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=Ron1234.
    ports:
      - 9984:5984
    networks:
      - test

  mysql5:
    container_name: mysql5
    image: mysql
    environment:
     - MYSQL_PASSWORD=Ron1234.
     - MYSQL_ALLOW_EMPTY_PASSWORD=false
     - MYSQL_RANDOM_ROOT_PASSWORD=Ron1234.
    ports:
      - 10984:5984
    networks:
      - test

  peer0.laboratory.com:
    container_name: peer0.laboratory.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=LaboratoryMSP 

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer0.laboratory.com
      - CORE_PEER_ADDRESS=peer0.laboratory.com:12010
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12010
      - CORE_PEER_CHAINCODEADDRESS=peer0.laboratory.com:12011
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12011
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.laboratory.com:12510
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.laboratory.com:12010
      

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=MYSQL
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_MYSQLDBADDRESS=mysql4:5984
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_PASSWORD=Ron1234.
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - mysql4
    ports:
      - 12010:12010
    volumes:
      - ./crypto-config/peerOrganizations/laboratory.com/peers/peer0.laboratory.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laboratory.com/peers/peer0.laboratory.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test

  peer1.laboratory.com:
    container_name: peer1.laboratory.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=LaboratoryMSP 

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer1.laboratory.com
      - CORE_PEER_ADDRESS=peer1.laboratory.com:12510
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12510
      - CORE_PEER_CHAINCODEADDRESS=peer1.laboratory.com:12511
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12511
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.laboratory.com:12510
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.laboratory.com:12510

      - CORE_LEDGER_STATE_STATEDATABASE=MYSQL
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_MYSQLDBADDRESS=mysql5:5984
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_MYSQLDBCONFIG_PASSWORD=Ron1234.
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 12510:12510
    volumes:
      - ./crypto-config/peerOrganizations/laboratory.com/peers/peer1.laboratory.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/laboratory.com/peers/peer1.laboratory.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - test