version: '2'

networks:
  test:

services:
  ca_pharmacy:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.pharmacy.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=4010
    ports:
      - "4010:4010"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/pharmacy:/etc/hyperledger/fabric-ca-server
    container_name: ca.pharmacy.com
    hostname: ca.pharmacy.com
    networks:
      - test
